name: Destroy

on:
  workflow_dispatch:

jobs:
  build-analyze-scan:
    name: Destroy
    runs-on: [self-hosted, git-workflow]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - name: Destroy Containers
        run: | 
          docker stop game
          docker rm game
        
      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name EKS_CLOUD

      - name: Destroy Kubernetes Deployments
        run: kubectl delete -f manifests/deployment-service.yml
  
      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubactions-eks'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Destroy Resources
        run: terraform destroy --auto-approve
