name: "Terraform"

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed

jobs:
  setup:
    name: "Terraform"
    runs-on: [self-hosted, git-workflow]
    steps:
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve