name: Terraform

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed
    status: success

jobs:
  setup:
    name: Setup
    runs-on: [self-hosted, git-workflow]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check and Create S3 and DynamoDB Resources
        run: |
          sudo chmod +x ./aws-prerequisite-resources.sh
          ./aws-prerequisite-resources.sh

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

  cleanup:
    name: Cleanup
    runs-on: [self-hosted, git-workflow]
    needs: Setup
    if: failure()
    steps:
      - name: Destroy Terraform Resources
        run: terraform destroy -auto-approve || true

      - name: Delete DynamoDB Table
        run: |
          aws dynamodb delete-table --table-name "terraform-state-locking-table" --region ap-south-1 || true

      - name: Delete S3 Bucket
        run: |
          aws s3api delete-bucket --bucket your-terraform-state-bucket --region ap-south-1 || true
