name: Terraform

on:
  workflow_run:
    workflows: [Script]
    types:
      - completed
    status: success

jobs:
  setup:
    name: "Terraform"
    runs-on: [self-hosted, git-workflow]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Create Backend
        run: mv backend.txt backend.tf

      - name: Initialize Backend
        run: terraform init

      - name: Initialize Backend
        run: terraform init -migrate-state